version: "3.7"
services:
  scheduler:
    build: ./scheduler
    depends_on:
      - worker
    networks:
      - vauth-message
  worker:
    build: ./worker
    depends_on:
      - nats
    networks:
      - vauth-message
      - vauth-backend
    environment:
    - VSPHERE_SERVER=${VSPHERE_SERVER}
    - VSPHERE_USERNAME=${VSPHERE_USERNAME}
    - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
    - VSPHERE_DATACENTER=${VSPHERE_DATACENTER}
  syncer:
    build: ./syncer
    depends_on:
      - nats
      - worker
    networks:
      - vauth-message
    environment:
    - VSPHERE_SERVER=${VSPHERE_SERVER}
    - VSPHERE_USERNAME=${VSPHERE_USERNAME}
    - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
    - VSPHERE_DATACENTER=${VSPHERE_DATACENTER}
  watcher:
    build: ./watcher
    depends_on:
      - nats
      - worker
    networks:
      - vauth-message
    environment:
    - VSPHERE_SERVER=${VSPHERE_SERVER}
    - VSPHERE_USERNAME=${VSPHERE_USERNAME}
    - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
    - VSPHERE_DATACENTER=${VSPHERE_DATACENTER}
  nats:
    image: nats:latest
    ports: 
      - "4222:4222"
    networks:
      - vauth-message
  backend:
    build: ./backend
    ports:
    - "443:443"
    depends_on:
      - cockroachdb
      - nats
    networks:
      - vauth-backend
      - vauth-message
      - vauth-database
  cockroachdb:
    image: cockroachdb/cockroach:v19.1.5
    ports:
     - "8080:8080"
    networks:
      - vauth-database
    command: ["start","--insecure"]
    secrets:
      - db_cert
      - db_key
    volumes:
      - database-volume:/cockroach/cockroach-data

secrets:
   db_cert:
     file: ./backend/cert.pem
   db_key:
     file: ./backend/key.pem

networks:
  vauth-backend:
  vauth-message:
  vauth-database:

volumes:
  database-volume: