version: "3.7"
services:
  ui:
    build: ./ui
    networks:
      - vauth-backend    
    depends_on:
      - backend
    ports:
      - 4200:4200
  scheduler:
    build: ./scheduler
    depends_on:
      - worker
    networks:
      - vauth-message
  worker:
    build: ./worker
    depends_on:
      - nats
    networks:
      - vauth-message
      - vauth-backend
    environment:
    - VSPHERE_SERVER=${VSPHERE_SERVER}
    - VSPHERE_USERNAME=${VSPHERE_USERNAME}
    - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
    - VSPHERE_DATACENTER=${VSPHERE_DATACENTER}
  syncer:
    build: ./syncer
    depends_on:
      - nats
      - worker
    networks:
      - vauth-message
    environment:
    - VSPHERE_SERVER=${VSPHERE_SERVER}
    - VSPHERE_USERNAME=${VSPHERE_USERNAME}
    - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
    - VSPHERE_DATACENTER=${VSPHERE_DATACENTER}
  watcher:
    build: ./watcher
    depends_on:
      - nats
      - worker
    networks:
      - vauth-message
    environment:
    - VSPHERE_SERVER=${VSPHERE_SERVER}
    - VSPHERE_USERNAME=${VSPHERE_USERNAME}
    - VSPHERE_PASSWORD=${VSPHERE_PASSWORD}
    - VSPHERE_DATACENTER=${VSPHERE_DATACENTER}
  nats:
    image: nats:latest
    ports: 
      - "4222:4222"
    networks:
      - vauth-message
  backend:
    build: ./backend
    ports:
    - "443:443"
    depends_on:
      - db
      - nats
    networks:
      - vauth-backend
      - vauth-message
      - vauth-database
    volumes:
      - ${PWD}/backend:/ssl/certs
    secrets:
      - ca.crt
  db:
    image: cockroachdb/cockroach:v19.1.5
    hostname: db
    container_name: db
    ports:
     - "8080:8080"
    networks:
      - vauth-database
    command: ["start","--certs-dir=/run/secrets","--listen-addr=db","--advertise-addr=db"]
    secrets:
      - ca.key
      - ca.crt
      - node.crt
      - node.key
    volumes:
      - database-volume:/cockroach/cockroach-data

secrets:
   ca.key:
     file: database/ca.key
   ca.crt:
     file: database/ca.crt
   node.crt:
     file: database/node.crt
   node.key:
     file: database/node.key
   db_key:
     file: backend/key.pem

networks:
  vauth-backend:
  vauth-message:
  vauth-database:

volumes:
  database-volume: