apiVersion: v1
kind: Namespace
metadata:
  name: vauth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere-config
  namespace: vauth
data:
  VSPHERE_SERVER: grtvcenter01.grt.local
  VSPHERE_USERNAME: vauth@vsphere.local
  VSPHERE_PASSWORD: Hashicorp1#
  VSPHERE_DATACENTER: GRT
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth
  namespace: vauth
  labels:
    name: vauth
spec:
  containers:
  - name: vauth
    image: public.ecr.aws/i4r5n0t9/vauth
    envFrom:
      - configMapRef:
          name: vsphere-config
