apiVersion: v1
kind: Namespace
metadata:
  name: vauth
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth-scheduler
  namespace: vauth
  labels:
    name: vauth-scheduler
spec:
  containers:
  - name: vauth-scheduler
    image: martezr/vauth-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth-worker
  namespace: vauth
  labels:
    name: vauth-worker
spec:
  containers:
  - name: vauth-worker
    image: martezr/vauth-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth-syncer
  namespace: vauth
  labels:
    name: vauth-syncer
spec:
  containers:
  - name: vauth-syncer
    image: martezr/vauth-syncer
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth-watcher
  namespace: vauth
  labels:
    name: vauth-watcher
spec:
  containers:
  - name: vauth-watcher
    image: martezr/vauth-watcher
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth-backend
  namespace: vauth
  labels:
    name: vauth-backend
spec:
  containers:
  - name: vauth-backend
    image: martezr/vauth-backend