apiVersion: v1
kind: Namespace
metadata:
  name: vauth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vauth-config
  namespace: vauth
data:
  VSPHERE_SERVER: grtvcenter01.grt.local
  VSPHERE_USERNAME: vauth@vsphere.local
  VSPHERE_PASSWORD: Hashicorp1#
  VAULT_ADDRESS: https://grtmanage01.grt.local:8200
  VAULT_TOKEN: "s.ewdkchV1oqIwTxxI8G3INWVG"
  VAULT_APPROLE_MOUNT: approle
  WRAP_RESPONSE: true
  TLS_SKIP_VERIFY: true
---
apiVersion: v1
kind: Pod
metadata:
  name: vauth
  namespace: vauth
  labels:
    name: vauth
spec:
  containers:
  - name: vauth
    image: public.ecr.aws/i4r5n0t9/vauth
    envFrom:
      - configMapRef:
          name: vauth-config
